name: hackathon
description: Download IO Hackathon Flutter app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  scoped_model: ^1.0.1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_analytics: ^6.0.0
  google_sign_in: ^4.5.4
  google_maps_flutter: ^0.5.33
  cloud_firestore: ^0.14.0+2
  autocomplete_textfield: ^1.7.3
  dio: ^3.0.10
  geolocator: ^6.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.png
    - assets/images/beehive.png

